# SPDX-License-Identifier: MIT
---
- name: Assert crypto_policies_policy is null or a string
  ansible.builtin.assert:
    that:
      - >-
        (crypto_policies_policy is none)
        or (crypto_policies_policy is string)
    fail_msg: >-
      crypto_policies_policy must be null or a string,
      got {{ crypto_policies_policy | type_debug }}
  when: crypto_policies_policy is defined

- name: Assert crypto_policies_transactional_update_reboot_ok is null or a boolean
  ansible.builtin.assert:
    that:
      - >-
        (crypto_policies_transactional_update_reboot_ok is none)
        or (crypto_policies_transactional_update_reboot_ok is sameas true)
        or (crypto_policies_transactional_update_reboot_ok is sameas false)
    fail_msg: >-
      crypto_policies_transactional_update_reboot_ok must be null or a boolean,
      got {{ crypto_policies_transactional_update_reboot_ok | type_debug }}
  when: crypto_policies_transactional_update_reboot_ok is defined
